#!/bin/sh

export HOME="/afs/cern.ch/exp/totem/scratch/jkaspar"

source "/cvmfs/cms.cern.ch/cmsset_default.sh"
cd "$CMSSW_BASE/src"
cmsenv

function SafeCmd()
{
	echo ""
	echo ">> SafeCmd: $@"
	for i in {1..10}
	do
		echo "* attempt $i:"
		"$@" && return 0
		sleep 5
	done
	echo "* giving up..."
	return 1
}

# define directories
job_dir="$JOB_DIR"

(
# run the process
cd "$job_dir"

$COMMAND

) &> "$job_dir/$JOB_LOG_FILE"
